---
apiVersion: batch/v1
kind: Job
metadata:
  name: database-init
  namespace: playground
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: people
        environment: dev
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: people-db-init
          image: people-db-init
          env:
            - name: PGHOST
              value: "yb-tservers.yugabytedb-system"
            - name: PGPORT
              value: "5433"
            - name: PGUSER
              value: "yugabyte"
            - name: PGPASSWORD
              value: "yugabyte"
            - name: PGDATABASE
              value: "yugabyte"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
              ephemeral-storage: 10Mi
            requests:
              cpu: 500m
              memory: 100Mi
              ephemeral-storage: 10Mi
      initContainers:
        - name: wait-for-db
          image: busybox:1.28
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 500m
              memory: 100Mi
              ephemeral-storage: 10Mi
            requests:
              cpu: 500m
              memory: 100Mi
              ephemeral-storage: 10Mi
          command:
            [
              "sh",
              "-c",
              "until nslookup yb-tservers.yugabytedb-system; do echo waiting for yb-tservers; sleep 2; done",
            ]
      restartPolicy: Never
  backoffLimit: 4
