---
apiVersion: v1
kind: Pod
metadata:
  name: sandbox
spec:
  containers:
    - name: sandbox
      image: ghcr.io/carhartl/k8s-playground/sandbox:latest
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 100Mi
