---
apiVersion: skaffold/v4beta2
kind: Config
manifests:
  kustomize:
    paths:
      - infra/manifests/dev
build:
  artifacts:
    - image: ghcr.io/carhartl/k8s-playground/app
      context: app
    - image: ghcr.io/carhartl/k8s-playground/database-init
      context: data
deploy:
  helm:
    releases:
      - name: kube-prometheus-stack
        repo: https://prometheus-community.github.io/helm-charts
        remoteChart: kube-prometheus-stack
        version: 44.2.1
        namespace: monitoring
        createNamespace: true
      - name: kyverno
        repo: https://kyverno.github.io/kyverno/
        remoteChart: kyverno
        version: 2.7.2
        namespace: kyverno
        createNamespace: true
      - name: kyverno-policies
        repo: https://kyverno.github.io/kyverno/
        remoteChart: kyverno-policies
        version: 2.7.2
        namespace: kyverno
        createNamespace: true
        setValues:
          podSecurityStandard: restricted
          validationFailureAction: enforce
          validationFailureActionOverrides:
            all:
              - action: audit
                namespaces:
                  - monitoring
                  - yugabyte
      - name: yugabyte
        repo: https://charts.yugabyte.com
        remoteChart: yugabyte
        version: 2.17.0
        namespace: yugabyte
        createNamespace: true
        setValues:
          podSecurityContext.enabled: true
          enableLoadBalancer: false
          replicas.master: 1
          replicas.tserver: 1
          resource.master.requests.cpu: 0.5
          resource.master.requests.memory: 0.5Gi
          resource.tserver.requests.cpu: 0.5
          resource.tserver.requests.memory: 0.5Gi
  kubectl:
    flags:
      # Apply server-side, so we don't run into:
      #   CustomResourceDefinition.apiextensions.k8s.io "policies.kyverno.io" is invalid:
      #     metadata.annotations: Too long: must have at most 262144 bytes
      apply: ["--server-side", "--namespace=playground"]
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubeContext: minikube
    portForward:
      - resourceType: deployment
        resourceName: people
        namespace: playground
        port: 8888
  - name: gke
    activation:
      - command: run
    manifests:
      kustomize:
        paths:
          - infra/manifests/gke
    deploy:
      kubeContext: gke
