---
apiVersion: skaffold/v4beta2
kind: Config
manifests:
  kustomize:
    paths:
      - infra/manifests/overlays/dev
    buildArgs:
      - --enable-helm
build:
  artifacts:
    - image: ghcr.io/carhartl/golang-k8s-playground/app
      context: app
    - image: ghcr.io/carhartl/golang-k8s-playground/database-init
      context: data
deploy:
  helm:
    releases:
      - name: kube-prometheus-stack
        repo: https://prometheus-community.github.io/helm-charts
        remoteChart: kube-prometheus-stack
        version: 44.2.1
        namespace: monitoring
        createNamespace: true
  kubectl:
    flags:
      # => CustomResourceDefinition.apiextensions.k8s.io "policies.kyverno.io" is invalid:
      #    metadata.annotations: Too long: must have at most 262144 bytes
      apply: ["--server-side"]
portForward:
  - resourceType: deployment
    resourceName: people
    namespace: playground
    port: 8888
