---
apiVersion: skaffold/v4beta2
kind: Config
manifests:
  kustomize:
    paths:
      - infra/manifests/dev
build:
  artifacts:
    - image: ghcr.io/carhartl/k8s-playground/app
      context: app
    - image: ghcr.io/carhartl/k8s-playground/database-init
      context: data
deploy:
  helm:
    releases:
      - name: kube-prometheus-stack
        repo: https://prometheus-community.github.io/helm-charts
        remoteChart: kube-prometheus-stack
        version: 45.27.2
        namespace: monitoring
        createNamespace: true
      - name: kuberhealthy
        repo: https://kuberhealthy.github.io/kuberhealthy/helm-repos
        remoteChart: kuberhealthy
        version: "92"
        namespace: kuberhealthy
        createNamespace: true
        setValues:
          prometheus:
            enabled: true
            serviceMonitor:
              enabled: true
              release: kube-prometheus-stack
              namespace: monitoring
              endpoints:
                # https://github.com/kuberhealthy/kuberhealthy/issues/726
                bearerTokenFile: ""
            prometheusRule:
              enabled: true
              release: kube-prometheus-stack
              namespace: monitoring
          check:
            daemonset:
              enabled: false
            deployment:
              enabled: false
            dnsInternal:
              enabled: false
      - name: kyverno
        repo: https://kyverno.github.io/kyverno/
        remoteChart: kyverno
        version: 2.7.2
        namespace: kyverno
        createNamespace: true
      - name: kyverno-policies
        repo: https://kyverno.github.io/kyverno/
        remoteChart: kyverno-policies
        version: 2.7.2
        namespace: kyverno
        createNamespace: true
        setValues:
          podSecurityStandard: restricted
          validationFailureAction: enforce
          validationFailureActionOverrides:
            all:
              - action: audit
                namespaces:
                  - monitoring
      - name: yugabyte
        repo: https://charts.yugabyte.com
        remoteChart: yugabyte
        version: 2.17.0
        namespace: yugabyte
        createNamespace: true
        setValues:
          podSecurityContext.enabled: true
          enableLoadBalancer: false
          replicas.master: 1
          replicas.tserver: 1
          resource.master.requests.cpu: 0.5
          resource.master.requests.memory: 0.5Gi
          resource.tserver.requests.cpu: 0.5
          resource.tserver.requests.memory: 0.5Gi
  kubectl:
    defaultNamespace: "playground"
    flags:
      # Apply server-side, so we don't run into:
      #   CustomResourceDefinition.apiextensions.k8s.io "policies.kyverno.io" is invalid:
      #     metadata.annotations: Too long: must have at most 262144 bytes
      apply: ["--server-side"]
profiles:
  - name: dev
    activation:
      - command: dev
    deploy:
      kubeContext: minikube
    portForward:
      - resourceType: deployment
        resourceName: people
        namespace: playground
        port: 8888
      - resourceType: service
        resourceName: kube-prometheus-stack-grafana
        namespace: monitoring
        port: 80
        localPort: 3000
      - resourceType: service
        resourceName: kuberhealthy
        namespace: kuberhealthy
        port: 80
        localPort: 3001
  - name: gke
    activation:
      - command: run
    manifests:
      kustomize:
        paths:
          - infra/manifests/gke
    deploy:
      kubeContext: gke
