---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac-service-account.yaml
patches:
  # It appears that in Yugabyte's helm chart the namespace value isn't picked up in the
  # template for the services. Thus these ended up in "default", breaking accessing the db
  # via `kubectl -n yugabyte exec -it yb-tserver-0 -- \
  #   sh -c "cd /home/yugabyte && ysqlsh -h yb-tserver-0 --echo-queries"`
  # => https://github.com/yugabyte/charts/issues/151
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: yugabyte
    target:
      version: v1
      kind: Service
      name: yb-.*
