---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: playground
resources:
  - ../base
  - database-init-job.yaml
  - deployment.yaml
  - service.yaml
  - pod-disruption-budget.yaml
  - rbac-service-account.yaml
  - people-api-check.yaml
