---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: people-api
  namespace: kuberhealthy
spec:
  runInterval: 30s
  timeout: 10m
  podSpec:
    containers:
      - name: http-check
        image: kuberhealthy/http-check:v1.5.0
        env:
          - name: CHECK_URL
            value: "http://people-service.playground.svc.cluster.local:8888/people"
          - name: COUNT
            value: "1"
          - name: REQUEST_TYPE
            value: "POST"
          - name: REQUEST_BODY
            value: '{"name":"John Doe"}'
        resources:
          requests:
            cpu: 15m
            memory: 100Mi
          limits:
            cpu: 15m
            memory: 100Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
    restartPolicy: Always
    terminationGracePeriodSeconds: 5
