---
apiVersion: v1
kind: Service
metadata:
  name: people-service
  namespace: playground
  labels:
    app: people
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: people
  type: LoadBalancer
