---
name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: app/go.mod
      - name: golangci-lint app
        uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376
        with:
          working-directory: app
      - name: golangci-lint data
        uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376
        with:
          working-directory: data
      - name: test
        working-directory: app
        run: go test ./...
